repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.379
    hooks:
      - id: pyright
        additional_dependencies:
          - pytest==8.0.2
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile dev-requirements.in
        entry: env CUSTOM_COMPILE_COMMAND="make dev-requirements.txt" pip-compile
        args: [dev-requirements.in]
        files: ^dev-requirements\.(in|txt)$
  - repo: local
    hooks:
      - id: check-additional-dependencies
        name: >-
            check additional dependencies for pre-commit hooks are represented in
            requirements files
        language: python
        entry: python check_additional_deps.py
        files: \.pre-commit-config\.yaml
        pass_filenames: false
        additional_dependencies:
            - pyyaml==6.0.1
      - id: sync-pre-commit-requirements
        name: >-
          make sure the versions used in pre-commit and those used in
          requirements files are in sync
        language: python
        entry: python sync_pre_commit_requirements.py
        files: (\.pre-commit-config\.yaml|dev-requirements\.txt)
        pass_filenames: false
        additional_dependencies:
            - pyyaml==6.0.1

ci:
  skip:
    - pyright
    - pip-compile
