repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.352
    hooks:
      - id: pyright
        additional_dependencies:
          - pytest==8.0.2
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.0
    hooks:
      - id: pip-compile
        name: pip-compile dev-requirements.in
        entry: env CUSTOM_COMPILE_COMMAND="make dev-requirements.txt" pip-compile
        args: [dev-requirements.in]
        files: ^dev-requirements\.(in|txt)$
