---
version: 2
jobs:
  lint-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ .Branch }}
            - v1-build-
      - restore_cache:
          keys:
            - v1-pip-{{ .Branch }}
            - v1-pip-
      - restore_cache:
          keys:
            - v1-precommit-{{ .Branch }}
            - v1-precommit-
      - run: pip install -r dev-requirements.txt
      - run: pre-commit run -a
      - run: make build/test
      - save_cache:
          paths:
            - build
          key: v1-build-{{ .Branch }}
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-pip-{{ .Branch }}
      - save_cache:
          paths: ~/.cache/pre-commit
          key: v1-precommit-{{ .Branch }}
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - d5:50:bd:8e:23:eb:14:3f:cf:15:87:42:0b:bf:e2:60
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H -t rsa ssh.eu.pythonanywhere.com > ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          paths: build
          keys:
            - v1-build-{{ .Branch }}
            - v1-build-
      - run: git remote add pythonanywhere fffergaleu@ssh.eu.pythonanywhere.com:/home/fffergaleu/fergalsiftttwebhooks.git
      - run: make build/deploy
      - save_cache:
          paths:
            - build
          key: v1-build-{{ .Branch }}
workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - lint-test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - lint-test
