---
version: 2
jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          paths: build
          key: v1-build-{{ .Branch }}
      - run: make build/test
      - save_cache:
          paths: build
          key: v1-build-{{ .Branch }}
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pre-commit-{{ .Branch }}
            - v1-pip-cache-{{ .Branch }}
      - run: pip install -r dev-requirements.txt
      - run: pre-commit run -a
      - save_cache:
          paths: ~/.cache/pre-commit
          key: v1-pre-commit-{{ .Branch }}
      - save_cache:
          paths: ~/.cache/pip
          key: v1-pip-cache-{{ .Branch }}
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - d5:50:bd:8e:23:eb:14:3f:cf:15:87:42:0b:bf:e2:60
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H -t rsa ssh.eu.pythonanywhere.com > ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          paths: build
          key: v1-build-{{ .Branch }}
      - run: git remote add pythonanywhere fffergaleu@ssh.eu.pythonanywhere.com:/home/fffergaleu/fergalsiftttwebhooks.git
      - run: make build/deploy
      - save_cache:
          paths: build
          key: v1-build-{{ .Branch }}
workflows:
  version: 2
  test-lint:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - lint:
          filters:
            branches:
              ignore:
                - main
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
